spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

logging:
  level:
    com.mtesazi: INFO
    org.springframework: WARN

services:
  department:
    base-url: ${DEPARTMENT_SERVICE_BASE_URL:http://department-service}
    connect-timeout: 2s
    read-timeout: 3s

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://discovery-server:8761/eureka}
