spring:
  application:
    name: employee-service
  cloud:
    config:
      enabled: ${SPRING_CLOUD_CONFIG_ENABLED:false}
      import-check:
        enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/employee_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:${CONFIG_IMPORT:}

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER:true}
    fetch-registry: ${EUREKA_CLIENT_FETCH:true}

server:
  port: ${SERVER_PORT:8081}

services:
  department:
    base-url: ${SERVICES_DEPARTMENT_BASE_URL:http://department-service}
    connect-timeout: 2s
    read-timeout: 3s