{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ include "enterprise-devops-platform.namespace" . }}
  labels:
    {{- include "enterprise-devops-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  gateway-jwt-secret: {{ .Values.secrets.jwt.gateway | quote }}
  auth-jwt-secret: {{ .Values.secrets.jwt.auth | quote }}
  database-username: {{ .Values.secrets.databases.username | quote }}
  database-password: {{ .Values.secrets.databases.password | quote }}
{{- end }}
