spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/auth_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:db/migration
  cloud:
    discovery:
      enabled: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://discovery-server:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}
    access-token-expiration: 900000
    refresh-token-expiration: 604800000
