spring:
  application:
    name: department-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    config:
      enabled: ${SPRING_CLOUD_CONFIG_ENABLED:true}
      import-check:
        enabled: false
