spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: ${SPRING_CLOUD_CONFIG_ENABLED:false}
      import-check:
        enabled: false
  config:
    import: optional:${CONFIG_IMPORT:}

services:
  auth:
    base-url: ${SERVICES_AUTH_BASE_URL:http://localhost:8083}
  employee:
    base-url: ${SERVICES_EMPLOYEE_BASE_URL:http://localhost:8081}
  department:
    base-url: ${SERVICES_DEPARTMENT_BASE_URL:http://localhost:8082}

server:
  port: ${SERVER_PORT:8080}

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER:true}
    fetch-registry: ${EUREKA_CLIENT_FETCH:true}
