spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          httpclient:
            connect-timeout: 2000
            response-timeout: 3s

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

services:
  employee:
    base-url: ${EMPLOYEE_SERVICE_BASE_URL:lb://employee-service}
  department:
    base-url: ${DEPARTMENT_SERVICE_BASE_URL:lb://department-service}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

security:
  auth:
    enabled: false
    public-paths:
      - /actuator/**
      - /swagger-ui/**
      - /v3/api-docs/**
